name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Adjust path to your requirements.txt inside the nested folder
          pip install -r wbc-classifier-app/requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: wbc-classifier-app/wbc-classifier-app
        env:
          # Point PYTHONPATH at the folder containing your modules
          PYTHONPATH: ${{ github.workspace }}/wbc-classifier-app/wbc-classifier-app
        run: pytest --maxfail=1 --disable-warnings -q
